{% set version = "0.4.0" %}
{% set name = "intake-sql" %}
{% set sha256 = "c79b0f7d484d569d990f32067cb01a5ef565522a657955d264b316a1b0c0d4c6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    # Replace deprecated SafeConfigParser with ConfigParser
    # Use perl for cross-platform compatibility
    - perl -pi -e 's/configparser\.SafeConfigParser/configparser.ConfigParser/g' versioneer.py
    - perl -pi -e 's/parser\.readfp/parser.read_file/g' versioneer.py
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - perl  # [not win]
  host:
    - python
    - pip
    - jinja2
    - wheel
  run:
    - python
    - intake >=0.3
    - pandas
    - sqlalchemy >2

test:
  imports:
    - intake_sql
  commands:
    - pip check
  requires:
    - pip
#keg
about:
  home: https://github.com/intake/intake-sql
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SQL table and catalog plugins for Intake
  description: |
    Plugin for Intake to read from SQL servers. This package enables reading
    data from a variety of SQL databases using SQLAlchemy. It provides both
    direct table reading and custom query capabilities for Intake catalogs.
  doc_url: https://intake-sql.readthedocs.io/
  dev_url: https://github.com/intake/intake-sql

extra:
  recipe-maintainers:
    - martindurant
