{% set version = "0.3.1" %}
{% set name = "intake-sql" %}
{% set sha256 = "38cc7802e1495a0892c7e4814220b8e66063783019c8bed7a2fde2120077710b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.5
    - pip
    - jinja2
  run:
    - python >=3.5
    - intake >=0.3
    - pandas
    - sqlalchemy

test:
  imports:
    - intake_sql

about:
  home: https://github.com/ContinuumIO/intake-sql
  license: BSD-2-Clause
  license_file: LICENSE
  summary: SQL table and catalog plugins for Intake

extra:
  recipe-maintainers:
    - martindurant
