travis:
  secure:
    BINSTAR_TOKEN: gzTbb7whvo5luH5YddibLfpgrr9sP7L3s3gdWxvOVLUCeyD1sxUrLTNwXslDUnqRgobJ8ThMB+aEwe9Wau2gjwJ+E0hO+p5BaaYl3qdAZP/CPM6N/b+mSm2Qh91IOTkg6mdQCbCH9D6ZuY8QbQxZoazMZ1WpfAhMNggFQaD/s84CJCmc9yWPAghPwTvMztPAQ3WbzA2cznc+2AAkvUjmAlToZz9sESd9+aej1OG6KDvFGidPq8GM2aApiYL4A6/xmG4paAOB89HEYIi3LEBqWQXjwEEacoy/NQocdSNOW/nB3WPv1oSn5fel+U+zvXJObUOQcE/6XAOcj18gan3624Ak3MPO5nDJ+iAnJVYi7AVxy80rvfNJ4R3S1641zcfslY1oHNDOec0fU5nyuDo5ozsI+3vai2n/WJl8F/uMOp2Jgr0BWSXrNmHdUewCDTbEmNeA6ySPS0npcu7se5AgNpP7ikqIM2rof/RNzsOmaqX7kQl5VSbZQgtzy8BdFXt33QJkl3RJ8NYUwrFRTcx51RL7mKjphph+pasFcDalIlGZW9dryzLuLBeI6ljwJw9xFHyWd0a3PaNQh02faq6SUh81deqAPM9HWg74eJQ56p/mN1VzjCYR2rjj7fmKeo6eRzUxzOaZKndy6akguUAmrV7d0RcTM0fajTO54kju4WA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
